"""services.shared.catalog_client - HTTP client for the A2A-Meta catalog.

The catalog in A2A-Meta (api/middleware/live_clone_catalog.py)
is the single source of truth for which clones are LIVE. This
client wraps HTTP access to that catalog. v0 uses a vendored
snapshot (catalog_snapshot.py) generated by scripts/sync_catalog.py;
v1 migrates to live HTTP.
"""
